// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI2EI5sbrOvn7GeQNxTuvwlzLiwmASn-s',
    appId: '1:1050461076702:web:988b07af7564016013d64f',
    messagingSenderId: '1050461076702',
    projectId: 'paksha',
    authDomain: 'paksha.firebaseapp.com',
    storageBucket: 'paksha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpGieu3kwX65d1ETw8KsLGx1MFRj_6slE',
    appId: '1:1050461076702:android:1d28689ff9509c6513d64f',
    messagingSenderId: '1050461076702',
    projectId: 'paksha',
    storageBucket: 'paksha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-8cXpMV0bMwEl3J49xlFOOIPMfHEL_4',
    appId: '1:1050461076702:ios:21530f35d4e0cf6f13d64f',
    messagingSenderId: '1050461076702',
    projectId: 'paksha',
    storageBucket: 'paksha.firebasestorage.app',
    iosBundleId: 'com.example.paksha',
  );
}
